# Generated by Django 3.2.3 on 2022-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('rate', models.CharField(max_length=10)),
                ('qty', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('gmail', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=45)),
            ],
        ),
    ]
