# Generated by Django 3.2.3 on 2022-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
