# Generated by Django 3.2.3 on 2022-09-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskapp', '0002_admins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admins',
        ),
    ]
