# Generated by Django 3.2.3 on 2022-10-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskapp', '0004_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('qty', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
