# Generated by Django 3.2.3 on 2022-10-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskapp', '0005_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
